#include "builtin.h"

char* builtin =
    "type Bool\n"
    "type Float64\n"
    "type Int64\n"
    "type None\n"
    "\n"
    "function print(value: t): None builtin\n"
    "interface ==[t](left: t, right: t): Bool\n"
    "interface !=[t](left: t, right: t): Bool\n"
    "interface <[t](left: t, right: t): Bool\n"
    "interface <=[t](left: t, right: t): Bool\n"
    "interface >[t](left: t, right: t): Bool\n"
    "interface >=[t](left: t, right: t): Bool\n"
    "interface *[t](left: t, right: t): t\n"
    "interface /[t](left: t, right: t): t\n"
    "interface %[t](left: t, right: t): t\n"
    "interface +[t](left: t, right: t): t\n"
    "interface -[t](left: t, right: t): t\n"
    "interface -'[t](negable: t): t\n"
    "\n"
    "function ==(left: Bool, right: Bool): Bool builtin\n"
    "function !=(left: Bool, right: Bool): Bool builtin\n"
    "function and(left: Bool, right: Bool): Bool builtin\n"
    "function or(left: Bool, right: Bool): Bool builtin\n"
    "function not(boolean: Bool): Bool builtin\n"
    "\n"
    "function ==(left: Float64, right: Float64): Bool builtin\n"
    "function !=(left: Float64, right: Float64): Bool builtin\n"
    "function <(left: Float64, right: Float64): Bool builtin\n"
    "function <=(left: Float64, right: Float64): Bool builtin\n"
    "function >(left: Float64, right: Float64): Bool builtin\n"
    "function >=(left: Float64, right: Float64): Bool builtin\n"
    "function *(left: Float64, right: Float64): Float64 builtin\n"
    "function /(left: Float64, right: Float64): Float64 builtin\n"
    "function +(left: Float64, right: Float64): Float64 builtin\n"
    "function -(left: Float64, right: Float64): Float64 builtin\n"
    "function -'(negable: Float64): Float64 builtin\n"
    "\n"
    "function ==(left: Int64, right: Int64): Bool builtin\n"
    "function !=(left: Int64, right: Int64): Bool builtin\n"
    "function <(left: Int64, right: Int64): Bool builtin\n"
    "function <=(left: Int64, right: Int64): Bool builtin\n"
    "function >(left: Int64, right: Int64): Bool builtin\n"
    "function >=(left: Int64, right: Int64): Bool builtin\n"
    "function *(left: Int64, right: Int64): Int64 builtin\n"
    "function /(left: Int64, right: Int64): Int64 builtin\n"
    "function %(left: Int64, right: Int64): Int64 builtin\n"
    "function +(left: Int64, right: Int64): Int64 builtin\n"
    "function -(left: Int64, right: Int64): Int64 builtin\n"
    "function -'(negable: Int64): Int64 builtin\n"
    "\n"
    "";