#[derive(Debug, Clone)]
pub struct Token {
    pub line: usize,
    pub column: usize,
    pub kind: TokenKind,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftCurly,
    RightCurly,
    Comma,
    Plus,
    Slash,
    Modulo,
    Star,
    Minus,
    Colon,
    Ampersand,
    Dot,
    Not,
    NotEqual,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    ColonEqual,
    Equal,
    EqualEqual,
    Be,
    Integer { literal: String },
    Float { literal: String },
    Identifier { literal: String },
    String { literal: String },
    StringLeft { literal: String },
    StringMiddle { literal: String },
    StringRight { literal: String },
    If,
    Else,
    While,
    Function,
    Interface,
    Builtin,
    Type,
    Case,
    True,
    False,
    Or,
    And,
    Use,
    Break,
    Continue,
    Return,
    Mut,
    New,
    Include,
    Extern,
    LinkWith,
    NewLine,
    EndOfFile,
}

pub fn get_literal(token: &Token) -> String {
    match &token.kind {
        TokenKind::LeftParen => "(".to_owned(),
        TokenKind::RightParen => "(".to_owned(),
        TokenKind::LeftBracket => "[".to_owned(),
        TokenKind::RightBracket => "]".to_owned(),
        TokenKind::LeftCurly => "{".to_owned(),
        TokenKind::RightCurly => "}".to_owned(),
        TokenKind::Comma => ",".to_owned(),
        TokenKind::Plus => "+".to_owned(),
        TokenKind::Slash => "/".to_owned(),
        TokenKind::Modulo => "%".to_owned(),
        TokenKind::Star => "*".to_owned(),
        TokenKind::Minus => "-".to_owned(),
        TokenKind::Colon => ":".to_owned(),
        TokenKind::Ampersand => "&".to_owned(),
        TokenKind::Dot => ".".to_owned(),
        TokenKind::Not => "not".to_owned(),
        TokenKind::NotEqual => "!=".to_owned(),
        TokenKind::Greater => ">".to_owned(),
        TokenKind::GreaterEqual => ">=".to_owned(),
        TokenKind::Less => "<".to_owned(),
        TokenKind::LessEqual => "<=".to_owned(),
        TokenKind::ColonEqual => ":=".to_owned(),
        TokenKind::Equal => "=".to_owned(),
        TokenKind::EqualEqual => "==".to_owned(),
        TokenKind::Be => "be".to_owned(),
        TokenKind::Integer { literal } => literal.clone(),
        TokenKind::Float { literal } => literal.clone(),
        TokenKind::Identifier { literal } => literal.clone(),
        TokenKind::String { literal } => format!("\"{literal}\""),
        TokenKind::StringLeft { literal } => format!("\"{literal}\""),
        TokenKind::StringMiddle { literal } => format!("\"{literal}\""),
        TokenKind::StringRight { literal } => format!("\"{literal}\""),
        TokenKind::If => "".to_owned(),
        TokenKind::Else => "".to_owned(),
        TokenKind::While => "".to_owned(),
        TokenKind::Function => "".to_owned(),
        TokenKind::Interface => "".to_owned(),
        TokenKind::Builtin => "".to_owned(),
        TokenKind::Type => "".to_owned(),
        TokenKind::Case => "".to_owned(),
        TokenKind::True => "".to_owned(),
        TokenKind::False => "".to_owned(),
        TokenKind::Or => "".to_owned(),
        TokenKind::And => "".to_owned(),
        TokenKind::Use => "".to_owned(),
        TokenKind::Break => "".to_owned(),
        TokenKind::Continue => "".to_owned(),
        TokenKind::Return => "".to_owned(),
        TokenKind::Mut => "".to_owned(),
        TokenKind::New => "".to_owned(),
        TokenKind::Include => "".to_owned(),
        TokenKind::Extern => "".to_owned(),
        TokenKind::LinkWith => "".to_owned(),
        TokenKind::NewLine => "".to_owned(),
        TokenKind::EndOfFile => "".to_owned(),
    }
}
