name: Build and test

on:
  push:
    branches:
      - main
    
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up LLVM
      run: ./get_llvm.py

    - name: Build
      run: ./build.py

    - name: Create folder for diamond executable
      run: mkdir build && mv diamond build/diamond

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: diamond-linux
        path: build

  test_linux:
    runs-on: ubuntu-latest
    needs: build_linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: diamond-linux
        path: diamond-linux
    
    - name: Get diamond out of folder and make executable
      run: mv diamond-linux/diamond diamond && chmod -R +x diamond

    - name: Run tests
      run: ./test.py

  build_macos:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up LLVM
      run: ./get_llvm.py

    - name: Build
      run: ./build.py

    - name: Create folder for diamond executable
      run: mkdir build && mv diamond build/diamond

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: diamond-macos
        path: build

  test_macos:
    runs-on: macos-14
    needs: build_macos

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: diamond-macos
        path: diamond-macos
    
    - name: Get diamond out of folder and make executable
      run: mv diamond-macos/diamond diamond && chmod -R +x diamond

    - name: Run tests
      run: ./test.py
  
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up LLVM
      run: python get_llvm.py

    - name: Build
      run: python build.py

    - name: Create folder for diamond executable
      run: mkdir build && move diamond.exe build/diamond.exe

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: diamond-windows
        path: build

  test_windows:
    runs-on: windows-latest
    needs: build_windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: diamond-windows
        path: diamond-windows
    
    - name: Get diamond out of folder and make executable
      run: move diamond-windows/diamond.exe diamond.exe

    - name: Run tests
      run: python test.py